[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tonto2"
authors = [{name = "Chuck Rhode", email = "CRhode@LacusVeris.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Development Status :: 3 - Alpha",
  "Environment :: X11 Applications :: Qt",
  "Intended Audience :: End Users/Desktop",
  "Natural Language :: English",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: Unix",
  "Programming Language :: Python :: 3",
  "Topic :: Utilities",
]
requires-python = ">=3.9"
version = "2.1.3"
description = "Tonto2 is a personal address-list, calendar, notepad, and so much more."
keywords = [
  "Lists",
  "Calendars",
  "Appointments",
  "Contacts",
  "Addresses",
  "Telephone Numbers",
  "Phone Numbers",
  "People",
  "Bookmarks",
  "Favorites",
  "Passwords",
  "Notes",
  "Cardfiles",
  "Bibliography",
  "Bibliographies",
]

[project.gui-scripts]
tonto2 = "tonto2:run_tonto2"

[project.scripts]
tonto2_conv_adr = "tonto2:run_tonto2_conv_adr"
tonto2_conv_cal = "tonto2:run_tonto2_conv_cal"

[project.urls]
Home = "https://LacusVeris.com/Tonto2/Docs/en"

[tool.flit.external-data]
directory = "data"
