[package]
name = "DeepFilterDataLoader"
version = "0.5.6"
authors = ["Hendrik SchrÃ¶ter"]
edition = "2021"
rust-version = "1.60"
resolver = "2"

[lib]
name = "libdfdata"
crate-type = ["cdylib"]
path = "src/lib.rs"

[features]
timings = ["deep_filter/timings"]
hdf5-static = ["deep_filter/hdf5-static"]

[dependencies]
deep_filter = { features = ["dataset", "vorbis", "flac"], path = "local_dependencies/deep_filter" }
pyo3 = { version = "0.19", default_features = true, features = [
  "extension-module",
] }
numpy = "0.19"
log = { version = "0.4", features = ["std"] }
crossbeam-channel = "^0.5"
ndarray = "^0.15"
