[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "intelligent-sales-core"
version = "1.0.14"
authors = [
  { name="Marc Vea", email="marc.vea@code.seat" },
]
description = "Globally shared modules in all Intelligent-Sales"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
]

[project.urls]
"Homepage" = "https://pypi.org/project/intelligent-sales-core/"
"GitHub" = "https://github.com/seatcode/intelligentsales-core"