[tool.poetry]
name = "badev"
version = "1.7.27"
description = "The BombSquad Modding Helper"
authors = ["Aeliux <itsaeliux@gmail.com>"]
license = "MIT"
readme = "README.md"
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Topic :: Text Editors :: Integrated Development Environments (IDE)"
]
packages = [
    { include = "babase", from = "src/assets/ba_data/python" },
    { include = "baclassic", from = "src/assets/ba_data/python" },
    { include = "baplus", from = "src/assets/ba_data/python" },
    { include = "bascenev1", from = "src/assets/ba_data/python" },
    { include = "bascenev1lib", from = "src/assets/ba_data/python" },
    { include = "bauiv1", from = "src/assets/ba_data/python" },
    { include = "bauiv1lib", from = "src/assets/ba_data/python" },
    { include = "baenv.py", from = "src/assets/ba_data/python" }
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.dev.dependencies]
commitizen = "^3.5.2"
pre-commit = "^3.3.3"


[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version_provider = "poetry"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
