[tool.poetry]
name = "versionedfunction"
version = "0.9.57"
description = "Sometimes you want to be able to dynamically call different versions of a function"
authors = ["John Heintz <john@gistlabs.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
