[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mass_analytics"
version = "1.3.3"
authors = [
  { name="Selim", email="alouiniselim@gmail.com" },
]
description = "Streamline data preprocessing and enhance analysis with our Powerful Data Preparation Package."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
        "numpy==1.25.1",
        "pandas==2.0.3",
        "plotly==5.15.0",
        "streamlit==1.24.1",
        "openpyxl",
        "tqdm",
        "fuzzywuzzy",
        "python-Levenshtein"
    ]
