[tool.poetry]
name = "bkwmediatools"
version = "0.1.1"
description = "Retrieving targeted media news about dredging, specific dredging projects, and news about competitors within the dredging industry."
authors = ["Mariam Safieldin <mariam.safieldin@boskalis.com>"]
license = "Boskalis"
readme = "README.md"
packages = [
    { include = "bkwmediatools" }
]
[tool.poetry.dependencies]
python = ">=3.8,<4.0"
gensim = "4.3.1"
deep-translator = "1.11.4"
requests = "2.31.0"
beautifulsoup4 = "4.12.2"
pandas = "1.5.3"
nltk = "3.6.3"
python-dotenv = "1.0.0"
azure-cognitiveservices-search-newssearch = "2.0.0"
azure-data-tables = "12.4.3"
eventregistry = "9.1"
langdetect = "1.0.9"

[tool.poetry.dev-dependencies]
black = "*"
pipenv-to-requirements = "*"
pre-commit = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
