[package]
name = "typos-vars"
version = "0.8.11"
description = "Source Code Spelling Correction"
readme = "../../README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
license= "MIT OR Apache-2.0"
repository= "https://github.com/crate-ci/typos"
edition= "2021"
rust-version= "1.65.0"  # MSRV
include= [
  "build.rs",
  "src/**/*",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "benches/**/*",
  "examples/**/*"
]

[dependencies]
unicase = "2.6"
dictgen = { version = "^0.2", path = "../dictgen" }
varcon-core = { version = "^4.0", path = "../varcon-core", features = ["flags"] }
