[tool.poetry]
name = "Medl"
version = "0.1.7"
description = "Music Explorer and DownLoader"
authors = ["Billuc <billuc@hotmail.fr>"]
license = "MIT"
readme = "README.md"
packages = [{include = "medl"}]

keywords = ["medl", "music", "python", "metadata", "spotify", "youtube", "youtube music"]

homepage = "https://github.com/Billuc/Medl"
repository = "https://github.com/Billuc/Medl"
documentation = "https://github.com/Billuc/Medl"

classifiers = [
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Multimedia",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Utilities",
]

include = ["medl/py.typed"]

[tool.poetry.dependencies]
python = "^3.9"
pytube = "^15.0.0"
yt-dlp = "^2023.3.4"
mutagen = "^1.46.0"
rich = "^13.3.5"
beautifulsoup4 = "^4.12.2"
taipan-di = "0.0.7"
lyrics-client = "0.0.4"
mumee = "0.0.7"
yumee = "0.0.3"
static-ffmpeg = "^2.5"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
pylint = "^2.17.4"
mypy = "^1.3.0"
pandas = "^2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  ".", "medl"
]

[tool.black]
line-length = 92