[tool.poetry]
name = "pype-bin"
version = "0.1.0"
description = ""
authors = ["Naoya Yamashita <conao3@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{ include = "src/pype" }]

[tool.poetry.scripts]
pype = "pype.__main__:main"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-icdiff = "^0.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
