[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ether_dream"
version = "0.0.1"
authors = [
  { name="Genki Kondo", email="kondo.genki@gmail.com" },
]
description = "A Python interface for the Ether Dream laser DAC"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]